module Cobweb; end

require 'uri'
require 'resque'
require 'addressable/uri'
require 'digest/sha1'
require 'base64'
require 'absolutize'
require 'cobweb/version'
require 'cobweb/spider'
require 'cobweb/namespaced_redis'
require 'cobweb/content_link_parser'
require 'cobweb/process_job'
require 'cobweb/crawl_job'
require 'cobweb/crawl_finished_job'
